apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
spec:
  generators:
  - clusters: {} # run against all clusters
                 # provides the name and server values
  template:
    metadata:
      name: "{{name}}-guestbook"
      namespace: argocd
    spec:
      destination:
        namespace: default
        server: "{{server}}"
      project: default
      source:
        path: guestbook
        repoURL: https://github.com/argoproj/argocd-example-apps.git
      syncPolicy:
        automated:
          prune: true
