#!/usr/bin/env bash


kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

export password="$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo)"

echo "kubectl port-forward svc/argocd-server -n argocd 8080:443"

echo "argocd login localhost:8080 --username admin --password $password"


